var a = 1;
var b = 2.71888;
var c = 'H';
var d = "Hello World";
var e = true;
console.log( typeof a );
console.log( typeof b );
console.log( typeof c );
console.log( typeof d );
console.log( typeof e );